# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install git for cloning repositories
RUN apk add --no-cache git

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci --only=prod

# Copy source code
COPY src ./src

# Set entrypoint
ENTRYPOINT ["node", "src/index.js"]
